# Generated by Django 4.0.3 on 2022-03-11 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='like',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
