# Generated by Django 4.0.3 on 2022-03-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_list', '0003_rename_like_songs_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
